version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: demoforgreg-db
    environment:
      POSTGRES_DB: demoforgreg
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
